### ISSUE TITLE
why u set the param like this in ur code

### ISSUE THREAD

**Issue by 11721206** [Goutham88/R-Peak-Detector-using-CNN-s#2]
for i in range(150,650000-150,200):
this is code in ur file ecg_cnn.py, I just want to know why u set param 150 and 200 ?thx

**Comment by Goutham88** [comment]
Sorry for the delay.
150 is the midpoint for the 1st chunk. In the for loop, we take i-150 to i+150 as a chunk and process it.
Now, 200 is the distance between each chunk. After a gap of 200, we take a new chunk and process them.
Hope you got it.
